## EDUNET FOUNDATION - Self-Practice Exercise Notebook

### LAB 8 - Implementing Numpy Concepts in Python

Problem 1: Write a NumPy program to test whether none of the elements of a given array are zero.

In [3]:
import numpy as np
a = np.array(list(map(int,input().split())))
print("Array contains a Zero as a Element") if any(a==0) else print("Array doesn't contains a Zero as its Element")

Array doesn't contains a Zero as its Element


Problem 2: Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [16]:
a=np.append(np.zeros(10,dtype=int),np.ones(10,dtype=int))
a = np.append(a,[5]*10)
print(a)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


Problem 3: Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [14]:
import numpy.random as random
x = random.normal(170,200,15)
print(x)

[ 219.86127618  396.87748007  228.60282908  222.06458292  506.51679202
  229.32913762  512.55448089 -181.3472987   184.50989955   50.9969888
  451.13844851  102.95683709  400.8807027   347.58816279  628.62719502]


Problem 4: Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [32]:
s = np.array(random.normal(200,7,40),ndmin=2)
s.reshape(8,5)
print(s)

[[198.39401488 198.22478855 204.7142792  203.03739848 204.39347163
  206.90041165 200.09703196 200.22419933 209.17448518 192.8896429
  212.10522516 201.98064069 209.33441241 194.52388448 202.47748137
  194.74529895 180.25147387 184.39849957 199.74792195 183.06483306
  204.85529585 205.49961734 204.05153892 202.56766276 190.00949951
  196.55829627 207.73276975 201.7558874  190.61071964 205.73778628
  185.30073203 208.19366835 197.30699197 206.25230846 211.67631203
  195.52265307 209.05886997 198.67544279 195.69079293 202.5526794 ]]


Problem 5: Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [40]:
myarray = np.arange(1,17,1)
myarray=np.reshape(myarray,newshape=(4,4))
myarray[:,[0,-1]]=myarray[:,[-1,0]]
myarray[:,[1,2]]=myarray[:,[2,1]]
print(myarray)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


Problem 6: Write a NumPy program to swap rows and columns of a given array in reverse order.

In [42]:
swapped = myarray[::-1,::-1]
print(swapped)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Problem 7: Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [43]:
a = np.arange(1,11,1)
b = np.arange(11,21,1)
print(a*b)

[ 11  24  39  56  75  96 119 144 171 200]


Problem 8: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [45]:
arr = np.arange(2,11,1)
arr2 = arr.reshape(3,3)
print(arr2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Problem 9: Write a NumPy program to create a 3x3x3 array with random values.
Expected Output:

[[[ 0.48941799 0.58722213 0.43453926]
[ 0.94497547 0.81081709 0.1510409 ]
[ 0.66657127 0.29494755 0.48047144]]
[[ 0.02287253 0.95232614 0.32264936]
[ 0.67009741 0.25458304 0.16290913]
[ 0.15520198 0.86826529 0.9679322 ]]
[[ 0.13503103 0.02042211 0.24683897]
[ 0.97852158 0.22374748 0.10798856]
[ 0.62032646 0.5893892 0.16958144]]]

In [49]:
k = np.array(random.rand(27))
d = k.reshape(3,3,3)
print(d)

[[[0.29998758 0.35611704 0.43014887]
  [0.94790284 0.47869474 0.05634634]
  [0.93805842 0.33196893 0.13820893]]

 [[0.93640718 0.04132299 0.89584584]
  [0.4745848  0.74173922 0.33885419]
  [0.684352   0.67910741 0.18173495]]

 [[0.86046697 0.00799178 0.81776305]
  [0.51792511 0.99171695 0.42097484]
  [0.25899728 0.94992114 0.58789519]]]


Problem 10: Write a Python program to find the maximum and minimum value of a given flattened array.

In [54]:
gk = random.randint(100,size=(10))
print(gk)
print(np.max(gk),np.min(gk))

[ 5 79 26 33 86  0 60 60 88 47]
88 0


Problem 11: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.     
Expected Output:
Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

In [55]:
array1 = np.array([2.0, 3.0, 4.0, 5.0])
array2 = np.array([3.0, 6.0, 2.0, 20.0])
add_result = array1 + array2
subtract_result = array1 - array2
multiply_result = array1 * array2
divide_result = array1 / array2
print("Add:")
print(add_result)
print("Subtract:")
print(subtract_result)
print("Multiply:")
print(multiply_result)
print("Divide:")
print(divide_result)


Add:
[ 5.  9.  6. 25.]
Subtract:
[ -1.  -3.   2. -15.]
Multiply:
[  6.  18.   8. 100.]
Divide:
[0.66666667 0.5        2.         0.25      ]


Problem 12: Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [61]:
a = np.array([0,1,2,3,4,5,6])
b = np.array([0,1,8,27,64,125,216])
print(a**b)

[1, 1, 256, 2030534587, 0, 1277562581, 0]
[         1          1        256 2030534587          0 1277562581
          0]


Problem 13: Create a Python project to guess a number that has randomly selected.

In [62]:
import random

def guess_the_number():
    secret_number = random.randint(1, 100)
    attempts = 0

    print("Welcome to the Guess the Number game!")
    print("I have selected a number between 1 and 100. Try to guess it.")

    while True:
        try:
            guess = int(input("Enter your guess: "))
            attempts += 1

            if guess < secret_number:
                print("Too low! Try again.")
            elif guess > secret_number:
                print("Too high! Try again.")
            else:
                print(f"Congratulations! You guessed the number {secret_number} in {attempts} attempts.")
                break
        except ValueError:
            print("Invalid input. Please enter a valid number.")

if __name__ == "__main__":
    guess_the_number()


Welcome to the Guess the Number game!
I have selected a number between 1 and 100. Try to guess it.
Too low! Try again.
Too low! Try again.
Too high! Try again.
Too low! Try again.
Too low! Try again.
Too low! Try again.
Too low! Try again.
Too low! Try again.
Too high! Try again.
Congratulations! You guessed the number 48 in 10 attempts.


Problem 14: Write a NumPy program to create a 2D array with 1 on the border and 0 inside.        
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [63]:
rows, cols = 5, 5
array = np.zeros((rows, cols))

array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print("Original array:")
print(array)

print("\n1 on the border and 0 inside in the array:")
print(array)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Problem 15: Write a NumPy program to append values to the end of an array.                      
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [66]:
a = np.array([10,20,30])
res = np.concatenate((a,[40,50,60,70,80,90]))